### PR TITLE
Use libvirt filters for network security

### PR DESCRIPTION
**Pull request by yeungp**
Use libvirt default network filters, no-arp-spoofing, no-ip-spoofing, and no-mac-spoofing.
Use existing nova network filter nova-no-nd-reflection.
These filters add rules to the ebtables, and do not conflict with neutron security groups.

Closes-rally-bug: DE789 DE701 DE714 DE505
Implements: rally-task TA5323
Not-in-upstream: true

### CODE REVIEW

**Comment by yeungp** [comment]
http://wikicentral.cisco.com/display/OPENSTACK/Network+Security+using+Libvirt+Filters+-+DE789+DE711+DE714+DE505+DE345

**Comment by alop** [comment]
I assume this passed some functional testing, right?

**Comment by yeungp** [comment]
Only manual functional tests. I'm in the process of documenting the tests in
http://wikicentral.cisco.com/display/OPENSTACK/Network+Security+using+Libvirt+Filters+-+DE789+DE711+DE714+DE505+DE345

**Comment by alop** [comment]
:+1:

**Comment by retr0h** [comment]
Waiting for 1.0.10 to release before merging.

**Comment by markvoelker** [comment]
Hmmm...no unit tests for the new class defs?  Does that mean we're reliant on manual testing to catch problems caused by changes to this over time?

**Comment by yeungp** [comment]
Yes, libvirt filters are implemented in user space libvirt and kernel netfilters.

**Comment by markvoelker** [comment]
Ok.  I'm not super happy with adding more code that doesn't have accompanying tests, but understand the urgency.  I'd suggest adding a task to build some automated tests around these. +1

**Comment by retr0h** [comment]
Yeah, I have a hard time getting into the habit of writing code w/o tests even if we have urgency. :/

**Comment by alop** [comment]
This fails testing

**Pull request merged**
