### PR TITLE
Revert "Merge pull request #21 from CiscoSystems/de711"

### PR DESCRIPTION
**Pull request by alop**
This reverts commit cc5f138d02504e71d56fa0a33c88a8ab6e3a8546, reversing
changes made to 5bd9e48d9f8b53d4d3fffcf2c0d3bd1efc5468fa.

Automated tests fail with the changes introduced by this. This blocks subsequent builds

Not-in-upstream: True

### CODE REVIEW

**Comment by retr0h** [comment]
Can you explain this more?  Other than it reverts due to tests failing.  Can you explain why it was done in the first place and why reverting will not cause regression in the original change?  I don't have enough background knowledge to understand why this was originally done and reverted.

**Comment by alop** [comment]
I can't, I just know that the neutron tests failing is blocking me on subsequent work #30

**Comment by retr0h** [comment]
I would prefer not to revert, and allow @yeungp to correct her original patch.

**Comment by yeungp** [comment]
neutron tests failed because nova/network/neutronv2/api.py is not upgraded to 2014.2.4, and is not related to #21 or #30
I have a patch for api.py, but want to run more tests before checking it in

**Comment by yeungp** [comment]
My mistake.  My earlier checkin did break unit tests.  The work was done so long ago I just didn't remember.

**Comment by alop** [comment]
@yeungp if/when you get a new PR submitted, reference this one so I can close it out,

**Comment by alop** [comment]
Should use #32 instead

**Pull request closed without merging**
