### PR TITLE
Adds resume image after direct_snapshot

### PR DESCRIPTION
**Pull request by alop**
I found this logic bug in the direct snapshot code. Tested in svl3
Also makes the snapshot of "type snapshot" so it shows up in the list
of "boot from snapshot"

Closes-rally-bug: DE1343
Not-in-upstream: true

### CODE REVIEW

**Comment by retr0h** [comment]
Nice find.  Should run tests to make sure we don't introduce failures.

**Comment by alop** [comment]
Ran 539 tests in 23.152s

OK

**Comment by markvoelker** [comment]
Good catch...ideally I'd like to see this upstreamed and a test added for the condition.  At a minimum has an upstream bug been reported?

**Comment by alop** [comment]
Yes, I've notified inktank, and they've said "Thanks, I'll update my fork with this"
However, I don't know if that'll be today, next week, after the summit.
So, the idea was, we get this patch in, and if/when Inktank does their push, we can revert this specific commit in favor of theirs

**Comment by alop** [comment]
Functional testing: Created an instance, and then snapshot'd it, it's been up for over two hours.
Also verified thath launch works too

$ hostname
alop-test-hack
$ uptime
 16:00:56 up  2:10,  1 users,  load average: 0.00, 0.01, 0.00
$ 

$ hostname
bootfromsnap
$ uptime
 16:01:34 up 2 min,  1 users,  load average: 0.00, 0.00, 0.00
$

**Comment by alop** [comment]
Regarding tests for this specifically, it doesn't appear that test_libvirt.py does that at all. It defines "info" with power_state.RUNNING, as it's not actually getting a real power state from a real hypervisor.

**Comment by markvoelker** [comment]
Ah, ok, took me a minute to realize this was associated with the Ceph patches.  +1 then.

**Comment by kevinbringard** [comment]
Nice catch. +1

**Comment by kevinbringard** [comment]
Handing over to dewey for final approval

**Comment by retr0h** [comment]
:+1:

**Pull request merged**
