### PR TITLE
Gracefully handle consumer cancel notifications

### PR DESCRIPTION
**Pull request by zhencisco**
Back ported from oslo.messaging in Icehouse.
With mirrored queues and clustered rabbit nodes a queue is still
mastered by a single rabbit node. When the rabbit node dies an
election occurs amongst the remaining nodes and a new master is
elected. When a slave is promoted to master it will close all the
open channels to its consumers but it will not close the
connections. This is reported to consumers as a consumer cancel
notification (CCN). Consumers need to re-subscribe to these queues
when they recieve a CCN.

kombu 2.1.4+ reports CCNs as channel errors. This patch updates
the ensure function to be more inline with the upstream kombu
functionality. We now monitor for channel errors as well as
connection errors and initiate a reconnect if we detect an error.

Implements: rally-user-story US6888
Upstream-Review: https://review.openstack.org/#/c/77276/
Not-in-upstream: true

### CODE REVIEW

**Comment by alop** [comment]
:+1:

**Comment by UshF** [comment]
LGTM in the sense that it does exactly what it says on the tin: replicates the upstream change. I am ignorant of the effect this will have on our cluster though  == cautious  +1  :)

**Comment by signed8bit** [comment]
+1

**Comment by retr0h** [comment]
We probably want to apply these very same patches to the other services or at the very least neutron and cinder.

**Comment by retr0h** [comment]
+1

**Comment by zhencisco** [comment]
Thanks. Do we need to apply this patch to Ceilometer? I don't know if ceilometer will be used.

**Comment by retr0h** [comment]
Prob wouldn't hurt.

**Pull request merged**
