### PR TITLE
NoVNC verify origin header matches host

### PR DESCRIPTION
**Pull request by dave-mccowan**
Closes-rally-bug: DE1754
Not-in-upstream: True

### CODE REVIEW

**Comment by rickerc** [comment]
Test coverage would be good also

**Comment by dave-mccowan** [comment]
I have manually unit tested this patch for both cases covered (matching origin and mismatching origin).  Unfortunately, there are no unit tests for websocketproxy in Havana, so there is no place to add automated tests in cis-havana.  The patch needs to be reworked for /master, since exception handling has been reworked since havana.  I will add and fix unit tests in /master for the updated patch.

**Comment by retr0h** [comment]
I have validated the fix. +1

**Comment by rickerc** [comment]
See also https://github.com/CiscoSystems/nova/pull/36 -- which is just the squashed version of this

**Pull request closed without merging**
