### PR TITLE
Fixed failing tests

### PR DESCRIPTION
**Pull request by alop**
There were various issues with the tests, I later found out
that the original author hadn't written tests for havana
This now finishes ./run_tests clean

Closes-rally-bug: DE1186
Implements: rally-task: TA8264
Not-in-upstream: true

### CODE REVIEW

**Comment by markvoelker** [comment]
Hmm...say more to me about the test being removed?

**Comment by alop** [comment]
I'm double checking why, on the surface, I think there is a conflict in driver.py between the h4 release and the last code from jdurgin's fork. One sec.

**Comment by retr0h** [comment]
Lets leave the test in.  Might be a local problem, I don't see any mention of this test failing in the build system.

**Comment by retr0h** [comment]
Okay, lets give this a shot.  Hopefully builds clean.  Looks good from my perspective.

**Pull request merged**
