### PR TITLE
Force Hard reboot re-create instance folder

### PR DESCRIPTION
**Pull request by tiewei**
When use share storage like ceph, instance's disk data is in ceph,
instance's disk doesn't rely on local instance folder anymore. So
when rebooting a instance, we should create the instance folder if
it is missed.

Change-Id: I1826d850cd802143e70e0e573ff061e12c6e5a4a
Upstream-Review: https://review.openstack.org/#/c/110524/2
Backported-from: juno
Closes-rally-bug: DE1351

### CODE REVIEW

**Comment by alop** [comment]
Oh man, that's an oversight! I sure hope the upstream gets merged too, looks like just nit-pick about a comment.

:+1:

**Comment by tiewei** [comment]
It was merged to upstream

**Comment by scpham** [comment]
+1

**Comment by retr0h** [comment]
:+1:

**Pull request merged**
