### PR TITLE
Per aggregate filters from community

### PR DESCRIPTION
**Pull request by tiewei**
Cherry pick sahid's commit in order to make it working in havana release

Since AggregateDiskFilter has been merged in community and will release in Juno, This review request is cherry pick community version and did some adjustments in order to make it work in havana release.

Introduce AggregateDiskFilter to allow scheduler get "disk_allocation_ratio" configuration from aggregate metadata instead of nova.conf. 
Also, it provides a workaround to make DiskFilter compatible with RBD backended hosts. Because RBD backend hosts would not report ceph storage space left, DiskFilter always think their disks are not enough for instance with large disk allocation. With AggregateDiskFilter, we can add all rbd backended hosts in an aggregate and set a big enough "disk_allocation_ratio" value.

### CODE REVIEW

**Comment by markvoelker** [comment]
This change appears to break about 20 unit tests.....

> FAIL: nova.tests.scheduler.test_host_filters.HostFiltersTestCase.test_aggregate_core_filter_conflict_values
> FAIL: nova.tests.scheduler.test_host_filters.HostFiltersTestCase.test_aggregate_core_filter_default_value
> FAIL: nova.tests.scheduler.test_host_filters.HostFiltersTestCase.test_aggregate_core_filter_value_error
> FAIL: nova.tests.scheduler.test_host_filters.HostFiltersTestCase.test_aggregate_disk_filter_default_value
> FAIL: nova.tests.scheduler.test_host_filters.HostFiltersTestCase.test_aggregate_disk_filter_value_error
> FAIL: nova.tests.scheduler.test_host_filters.HostFiltersTestCase.test_aggregate_filter_num_iops_value
> FAIL: nova.tests.scheduler.test_host_filters.HostFiltersTestCase.test_aggregate_filter_num_iops_value_error
> FAIL: nova.tests.scheduler.test_host_filters.HostFiltersTestCase.test_aggregate_image_properties_isolation_multi_props_passes
> FAIL: nova.tests.scheduler.test_host_filters.HostFiltersTestCase.test_aggregate_image_properties_isolation_passes
> FAIL: nova.tests.scheduler.test_host_filters.HostFiltersTestCase.test_aggregate_image_properties_isolation_props_imgprops_passes
> FAIL: nova.tests.scheduler.test_host_filters.HostFiltersTestCase.test_aggregate_image_properties_isolation_props_namespace
> FAIL: nova.tests.scheduler.test_host_filters.HostFiltersTestCase.test_aggregate_image_properties_isolation_props_not_match2_fails
> FAIL: nova.tests.scheduler.test_host_filters.HostFiltersTestCase.test_aggregate_image_properties_isolation_props_not_match_fails
> FAIL: nova.tests.scheduler.test_host_filters.HostFiltersTestCase.test_aggregate_image_properties_isolation_props_with_meta_passes
> FAIL: nova.tests.scheduler.test_host_filters.HostFiltersTestCase.test_aggregate_ram_filter_conflict_values
> FAIL: nova.tests.scheduler.test_host_filters.HostFiltersTestCase.test_aggregate_ram_filter_default_value
> FAIL: nova.tests.scheduler.test_host_filters.HostFiltersTestCase.test_aggregate_ram_filter_value_error
> FAIL: nova.tests.scheduler.test_host_filters.HostFiltersTestCase.test_aggregate_type_filter
> FAIL: nova.tests.scheduler.test_host_filters.HostFiltersTestCase.test_metrics_filter_missing_metrics
> FAIL: nova.tests.scheduler.test_host_filters.HostFiltersTestCase.test_metrics_filter_pass

**Comment by markvoelker** [comment]
Thanks for fixing the tests.  This looks ok to me now; we just need a priority call as to whether this goes into 1.0.8 or 1.0.9.  As I'll probably be out of the office tomorrow, I'll give this a +1 and punt that decision to Dewey.

**Comment by retr0h** [comment]
This looks good.  However, we should add this to the cis-havana-staging branch, then we merge staging to this branch for 1.0.9.

IMO this should go out in 1.0.9 not 1.0.8 H3 + stable.

**Comment by tiewei** [comment]
@markvoelker @retr0h Thanks for your comments, will create a new pull request against cis-havana-staging branch.

**Pull request closed without merging**
